"""Adiciona tabelas do Marketplace

Revision ID: 2e72c72a6602
Revises: 4f50db79dd2e
Create Date: 2025-11-13 08:56:48.630566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e72c72a6602'
down_revision = '4f50db79dd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('metragem', sa.String(length=50), nullable=True),
    sa.Column('proprietario', sa.String(length=150), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('foto_capa', sa.String(length=255), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imovel_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imovel_fotos')
    op.drop_table('imoveis')
    # ### end Alembic commands ###
